// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4S3Yn8HS1WJwHA0vv2hWTEX464EFmcAs',
    appId: '1:135492546406:web:57b1195ff40759f34fe2a7',
    messagingSenderId: '135492546406',
    projectId: 'ai-chat-e2745',
    authDomain: 'ai-chat-e2745.firebaseapp.com',
    storageBucket: 'ai-chat-e2745.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDua0ihn3kL6MVeZQdOE0yfYbi3dU1BuuI',
    appId: '1:135492546406:android:69c4d3a1c4af24be4fe2a7',
    messagingSenderId: '135492546406',
    projectId: 'ai-chat-e2745',
    storageBucket: 'ai-chat-e2745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9BVE5jhNXGCwtiPXU4ib-OP4OUIZtfo',
    appId: '1:135492546406:ios:44434cec6fbbe4c44fe2a7',
    messagingSenderId: '135492546406',
    projectId: 'ai-chat-e2745',
    storageBucket: 'ai-chat-e2745.appspot.com',
    androidClientId: '135492546406-91abd4cr3jfkntt5i0tev1c4iot7q6ij.apps.googleusercontent.com',
    iosClientId: '135492546406-r89vo62cocvrk60dv1mvq0lvltpkjs42.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChat',
  );
}
